version: 2

project_name: fftools

before:
  hooks:
    - go mod tidy

builds:
  - id: asciify
    main: ./cmd/asciify/asciify.go
    binary: asciify
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILDER=goreleaser

  - id: asciitable
    main: ./cmd/asciitable/asciitable.go
    binary: asciitable
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILDER=goreleaser

  - id: bytecount
    main: ./cmd/bytecount/bytecount.go
    binary: bytecount
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILDER=goreleaser

  - id: certinfo
    main: ./cmd/certinfo/certinfo.go
    binary: certinfo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILDER=goreleaser

  - id: ghash
    main: ./cmd/ghash/ghash.go
    binary: ghash
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILDER=goreleaser

  - id: hexdumpc
    main: ./cmd/hexdumpc/hexdumpc.go
    binary: hexdumpc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILDER=goreleaser

  - id: hosty
    main: ./cmd/hosty/hosty.go
    binary: hosty
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILDER=goreleaser

  - id: unhexdump
    main: ./cmd/unhexdump/unhexdump.go
    binary: unhexdump
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILDER=goreleaser

  - id: unicount
    main: ./cmd/unicount/unicount.go
    binary: unicount
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILDER=goreleaser

  - id: uniwhat
    main: ./cmd/uniwhat/uniwhat.go
    binary: uniwhat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILDER=goreleaser

  - id: urly
    main: ./cmd/urly/urly.go
    binary: urly
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILDER=goreleaser

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]


homebrew_casks:
  - name: fftools
    binaries:
      - asciify
      - asciitable
      - bytecount
      - certinfo
      - ghash
      - hexdumpc
      - hosty
      - unhexdump
      - unicount
      - uniwhat
      - urly
    # manpages:
    # completions:
    directory: Casks
    skip_upload: true
    commit_author:
      name: Andrew Marcuse
      email: fileformat@gmail.com
    description: "Utilities for analyzing, viewing and fixing file formats."
    homepage: "https://tools.fileformat.info/"
    license: "GPL-3.0-or-later"
    repository:
      owner: FileFormatInfo
      name: fftools-tap
      # token:

nfpms:
  - id: fftools
    package_name: fftools
    vendor: FileFormatInfo
    homepage: "https://www.fileformat.info/"
    maintainer: Andrew Marcuse <fileformat@gmail.com>
    description: |-
      Utilities for analyzing, viewing and fixing file formats.
    license: GPL-3.0-and-later
    formats:
      - deb
      - rpm

report_sizes: true

#source:
#  enabled: true
#  name_template: "{{ .ProjectName }}.src"

upx:
  - enabled: true

#changelog:
#  sort: asc
#  filters:
#    exclude:
#      - "^docs:"
#      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
#  github:
#    owner: FileFormatInfo
#    name: fftools
