version: 2

project_name: fftools

before:
  hooks:
    - go mod tidy
    - ./bin/gen_manpages.sh

builds:
  - id: asciify
    main: ./cmd/asciify/asciify.go
    binary: asciify
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

  - id: asciitable
    main: ./cmd/asciitable/asciitable.go
    binary: asciitable
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

  - id: bytecount
    main: ./cmd/bytecount/bytecount.go
    binary: bytecount
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

  - id: certinfo
    main: ./cmd/certinfo/certinfo.go
    binary: certinfo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

  - id: hexdumpc
    main: ./cmd/hexdumpc/hexdumpc.go
    binary: hexdumpc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

  - id: unicount
    main: ./cmd/unicount/unicount.go
    binary: unicount
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

  - id: uniwhat
    main: ./cmd/uniwhat/uniwhat.go
    binary: uniwhat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X github.com/FileFormatInfo/fftools/internal.VERSION={{.Version}}
      - -X github.com/FileFormatInfo/fftools/internal.LASTMOD={{.Timestamp}}
      - -X github.com/FileFormatInfo/fftools/internal.COMMIT={{.ShortCommit}}
      - -X github.com/FileFormatInfo/fftools/internal.BUILDER=goreleaser

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
  #- files:
  #  - LICENSE.txt
  #  - manpages/*

homebrew_casks:
  - name: fftools
    binaries:
      - asciify
      - asciitable
      - bytecount
      - certinfo
      - hexdumpc
      - unicount
      - uniwhat
    # manpages:
    # completions:
    directory: pkg/cask
    skip_upload: true
    commit_author:
      name: Andrew Marcuse
      email: fileformat@gmail.com
    description: "Utilities for analyzing, viewing and fixing file formats."
    homepage: "https://tools.fileformat.info/"
    license: "GPL-3.0-or-later"
    repository:
      owner: FileFormatInfo
      name: fftools-tap
      # token:

nfpms:
  - id: fftools
    package_name: fftools
    vendor: FileFormatInfo
    homepage: "https://www.fileformat.info/"
    maintainer: Andrew Marcuse <fileformat@gmail.com>
    description: |-
      Utilities for analyzing, viewing and fixing file formats.
    license: GPL-3.0-and-later
    formats:
      - deb
      - rpm
#  - contents:
#      - src: ./manpages/
#        dst: /usr/share/man/man1/
#        type: dir
#        file_info:
#          mode: 0644


report_sizes: true

#source:
#  enabled: true
#  name_template: "{{ .ProjectName }}.src"

#upx:
#  - enabled: true

#changelog:
#  sort: asc
#  filters:
#    exclude:
#      - "^docs:"
#      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
#  github:
#    owner: FileFormatInfo
#    name: fftools
