name: build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '*.sh'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '*.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Build
        run: |
          bin/build.sh
